export {
  FUTURE_YOU_REPORT_TRIGGER_LABEL,
  FUTURE_YOU_REPORT_SHEET_TITLE,
  FUTURE_YOU_REPORT_SHEET_BODY,
  FUTURE_YOU_REPORT_SUBMIT_LABEL,
  FUTURE_YOU_REPORT_SUCCESS_MESSAGE,
  FUTURE_YOU_REPORT_ERROR_MESSAGE,
  FUTURE_YOU_REPORT_CATEGORY_OPTIONS,
  futureYouReportCategoryLabel,
} from "@newyouai/core";
