export {
  MAX_NUTRITION_ITEMS_PER_DAY,
  nutritionItemsCountForDay,
  canAppendNutritionItem,
  newNutritionItemId,
  PROTEIN_QUICK_ADD_PRESETS,
  buildNutritionLoggedItem,
  getRecentlyLoggedFoods,
  appendNutritionLoggedItem,
  removeNutritionLoggedItem,
  updateNutritionLoggedItem,
  appendNutritionPresetToDay,
  topProteinPresetsForQuickLog,
  addNutritionFavoriteToState,
  removeNutritionFavoriteFromState,
  toggleNutritionFavoriteInState,
  upsertNutritionUserFood,
  removeNutritionUserFood,
  removeNutritionPreset,
  nutritionUserFoodFromLoggedItem,
  appendNutritionUserFoodToState,
  updateNutritionUserFoodInState,
  removeNutritionUserFoodFromState,
  removeNutritionPresetFromState,
} from "@newyouai/core";
export type { NutritionQuickAddPreset } from "@newyouai/core";

export const QUICK_ADD_CHIP_STYLE = {
  padding: "10px 14px",
  borderRadius: 999,
  border: "0.5px solid rgba(255,255,255,0.14)",
  background: "rgba(255,255,255,0.08)",
  color: "#fff",
  fontSize: 13,
  fontWeight: 600,
  letterSpacing: "-0.02em",
} as const;
