export {
  ZERO_MACROS,
  effectiveNutritionTotalsForDateKey,
  manualTotalsForDateKey,
  nutritionPresetFingerprint,
  sumNutritionItems,
  stableLegacyNutritionLoggedAtMs,
  normalizeNutritionManualByDay,
  normalizeNutritionItemsByDay,
  mergePersistedNutritionDays,
  addNutritionFavorite,
  isNutritionFavorite,
  touchNutritionPresetById,
  normalizeNutritionPresets,
  normalizeNutritionUserFoods,
} from "@newyouai/core";
