export {
  defaultTrainingWeekdays,
  weekdayShort,
  weekdayFullName,
  weekdayMonStartIndex,
  nextTrainingDayFrom,
  resolveWorkoutDaysPerWeek,
  normalizeDayLabel,
  isTrainingDay,
  templateForDate,
  startOfWeekSunday,
  weekDateKeysSundayStart,
  startOfWeekMonday,
  weekDateKeysMondayStart,
} from "@newyouai/core";
