export {
  DEFAULT_WATER_DAILY_TARGET_OZ,
  WATER_QUICK_ADD_OZ,
  WATER_QUICK_ADD_L,
  WATER_TARGET_PRESETS_OZ,
  WATER_TARGET_PRESETS_L,
  FL_OZ_TO_L,
  L_TO_FL_OZ,
  normalizeWaterDailyTargetOz,
  normalizeWaterLogEntry,
  normalizeWaterLogByDay,
  mergeWaterLogByDay,
  totalWaterOzForDateKey,
  removeWaterLogEntry,
  clearWaterLogForDateKey,
  appendWaterLogEntry,
  formatWaterOz,
  formatWaterLitersFromOz,
  parseVolumeToOz,
  formatVolumeFromOz,
  formatWaterVolume,
  formatWaterVolumeAlt,
  waterQuickAddPresets,
  waterTargetPresets,
  formatWaterPreset,
} from "@newyouai/core";
