import type { AppState } from "./app-state";

/** Fields persisted locally and synced to Supabase JSONB. */
export type PersistedFitnessSlice = Pick<
  AppState,
  | "nutritionLog"
  | "nutritionManualByDay"
  | "nutritionItemsByDay"
  | "nutritionPresets"
  | "nutritionUserFoods"
  | "nutritionMeals"
  | "nutritionTargets"
  | "weightLog"
  | "progressPics"
  | "progressPicsLock"
  | "lastAdjustmentSundayKey"
  | "sundayReviewCompletedKey"
  | "weekFocusCommitments"
  | "weekFocusWeekStartKey"
  | "sundayCheckInHistory"
  | "adjustmentHistory"
  | "workout"
  | "customExercises"
  | "exerciseNotesByKey"
  | "workoutTemplates"
  | "workoutsCompletedByDay"
  | "streakEligibleByDay"
  | "fitnessStreakSnapshot"
  | "streakSessionBaseline"
  | "streakLossNoticeDismissedForKey"
  | "exercisePersonalBests"
  | "exerciseSessionHistoryByKey"
  | "workoutHistory"
  | "nightlyStretchCompletedArizonaKey"
  | "nightlyStretchBlockIdsByArizonaDay"
  | "displayName"
  | "habitTemplates"
  | "habitsDoneByDay"
  | "planStartIso"
  | "stepsTarget"
  | "progressGoal"
  | "unitPreferences"
  | "unitPreferencesChosen"
  | "experienceLevel"
  | "experienceLevelChosen"
  | "equipmentSetup"
  | "equipmentSetupChosen"
  | "restTimerDefaultSeconds"
  | "restTimerSecondsByExerciseKey"
  | "onboardingProfile"
  | "onboardingComplete"
  | "onboardingDraft"
  | "theme"
  | "subscriptionTier"
  | "futureYou"
  | "notificationPreferences"
  | "waterLogByDay"
  | "waterDailyTargetOz"
>;
